### ISSUE TITLE
Add Permissions for user roles from scanned directory

### ISSUE THREAD

**Issue by Natshah** [Vardot/module-installer-factory#9]
[Invalid permissions will trigger runtime exceptions in Drupal 10.](https://www.drupal.org/node/3193348) Permissions should be defined in a permissions.yml file or a permission callback.

The `skip_missing_permission_deprecation` flag that was added to the Role entity in [#2571235: [regression] Roles should depend on objects that are building the granted permissions](https://www.drupal.org/project/drupal/issues/2571235) and used in the core role migrations.

 
```
  # A special flag so we can migrate permissions that do not exist yet.
  # @todo Remove in https://www.drupal.org/project/drupal/issues/2953111.
  skip_missing_permission_deprecation:
    plugin: default_value
    default_value: true
```

[Issue #2953111: Only migrate role permissions that exist on the destination](https://www.drupal.org/project/drupal/issues/2571235)

It was removed from the `10.0.x` and `10.1.x` branch

Having a new function to Add Permissions for user roles from a scanned directory.

User roles creation will have no permissions in them in **Varbase Profile**.
```
user.role.anonymous.yml
user.role.authenticated.yml
user.role.content_admin.yml
user.role.editor.yml
user.role.seo_admin.yml
user.role.site_admin.yml
user.role.administrator.yml
```

After scanning all permissions in the `"config/permissions"` folder on each Varbase modules

Each **Varbase** component module will have its needed permissions in:

```
config/permissions/user.permissions.anonymous.yml
config/permissions/user.permissions.authenticated.yml
config/permissions/user.permissions.content_admin.yml
config/permissions/user.permissions.editor.yml
config/permissions/user.permissions.seo_admin.yml
config/permissions/user.permissions.site_admin.yml
```

With the list of all needed to grant Permissions after making sure all
dependencies for modules or dependencies on configs.

Following with the new **Drupal 10** standard 

When the **Extra Varbase component** is enabled. 
The needed permissions will be granted to the active user role.
